# Generated by Django 5.1.2 on 2024-10-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Draft", "Draft"),
                    ("Disabled", "Disabled"),
                    ("Featured", "Featured"),
                ],
                default="Active",
                max_length=100,
            ),
        ),
    ]
