# Generated by Django 5.1.2 on 2024-10-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
