# Generated by Django 5.1.2 on 2024-10-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_gallery_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.FileField(upload_to="Gallery"),
        ),
    ]
