# Generated by Django 5.1.2 on 2024-10-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_quote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
